import Foundation

struct ReleaseNoteEntry: Equatable, Identifiable {
  let version: String
  let build: Int
  let dateText: String
  let title: String
  let summary: String
  let highlights: [String]
  let previousHighlights: [String]
  let changelogURL: URL

  var id: Int { build }

  var displayVersion: String {
    CustomerVersionFormatter.appVersion(version: version, build: "\(build)")
  }
}

enum ReleaseNotes {
  static let fallbackChangelogURL = URL(
    string: "https://aixlg.com/mac/changelog/?v=20260908-free-open-source")!

  static let bundled: [ReleaseNoteEntry] = [
    ReleaseNoteEntry(
      version: "1.0.2",
      build: 216,
      dateText: "2026-09-08",
      title: "所有功能永久免费，感谢最初的支持",
      summary: "快捷键、截图、剪贴板、游目、披卷和听澜等所有功能永久免费，无需账号，没有使用期限。把好用的工具分享给朋友，让更多人认识小龙哥。",
      highlights: [
        "打开就能使用所有功能，不用登录、购买或邀请换取时长。",
        "感谢最早购买或收到赠送的 14 位朋友。既有的永久 AI 答疑支持继续保留，通过「联系小龙哥」发起求助。",
        "在设置中直接分享给朋友，让对方安装后也能免费使用。",
      ],
      previousHighlights: [
        "个人快捷键、设置与使用历史继续保留。",
        "官方签名、公证与软件更新的安全校验继续保留。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "1.0.1",
      build: 215,
      dateText: "2026-09-07",
      title: "现有功能永久免费，打开就能用",
      summary: "安装后，启动、截图、剪贴板、游目、披卷、听澜与现有系统工具都可以免费使用，无需登录，也没有试用到期。应用中心未来新增的独立功能会逐项标价，由你选择购买。",
      highlights: [
        "安装后直接使用现有全部功能；离线、没有账户或旧试用到期，都不会影响基础功能。",
        "打开应用中心查看现有工具，把官网链接分享给朋友，对方安装后也可以免费使用。",
        "查看后续更新时，现有功能的修复和维护都可以免费获取；未来独立新功能会说明价格与范围，目前不预售。",
        "原有设置、已购买许可与售后继续保留；五位早期付费朋友可在许可页面查看独立编号的“初代同行者”纪念章。",
        "查看菜单栏网速、打开常用窗口与恢复许可更稳定，已有快捷键和输入法设置继续沿用。",
      ],
      previousHighlights: [
        "邮箱验证后可以继续恢复许可，输错或过期时会直接显示下一步。",
        "已购买产品的永久使用和既有更新权益继续保留。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "1.0.0",
      build: 209,
      dateText: "2026-08-30",
      title: "邮箱验证后，恢复许可不再绕圈",
      summary: "邮箱验证成功后，即使暂时没找到许可或网络中断，也能直接重试恢复，不再把刚用过的验证码误报为过期。",
      highlights: [
        "请使用购买时填写的邮箱；已验证的邮箱会继续恢复许可，需要新验证码时会明确提示。按提示操作，就可以继续恢复许可。",
        "恢复许可的弹窗会直接显示结果和下一步，不用关闭窗口寻找错误提示。",
        "复制的验证码可以直接粘贴，也支持常见数字格式；输错、过期或已使用时，会给出对应提示。",
        "原有快捷键、个人设置和已购买许可都会保留。",
      ],
      previousHighlights: [
        "按住 Caps Lock 配合数字或字母，启动常用工具、截图，并打开游目、披卷与听澜。",
        "在微信、豆包等输入法里按 Shift，仍由输入法自己切换中英文。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 204,
      dateText: "2026-08-23",
      title: "Shift 交还输入法，常用设置更省事",
      summary: "在微信、豆包等输入法里按 Shift，就由输入法自己切换中英文，本 App 不会重复接管；按 Fn 仍会原样交给千问等语音软件。",
      highlights: [
        "轻按、长按、连按或配合字母使用 Shift，都不会再进入本 App 的输入法切换逻辑。",
        "打开“一键恢复小龙哥最佳配置”，可以先清理这台 Mac 的旧配置，再导入小龙哥当前最佳设置。",
        "打开“自定义菜单栏”，可以在一处设置菜单栏入口、系统健康卡片与显示方式，不用来回找。",
        "按 Caps + 1 完成区域截图后可以直接复制，不用再点确认。",
        "在千问等语音软件里按 Fn，可以由软件直接接收，不会夹带 Control 或 Option。",
      ],
      previousHighlights: [
        "按 App 设置输入法规则的能力继续保留，未设置规则的 App 不会被改动。",
        "打开测速窗口后，Codex 四轮连通检测会自动开始。",
        "下载、上传、延迟和抖动继续由你点击左球后才运行。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 197,
      dateText: "2026-08-16",
      title: "Shift 秒切更跟手，Fn 语音输入不再被打断",
      summary: "按一下 Shift，就可以直接使用 macOS 原生输入法切换；Fn 会原样交给千问等语音软件，不会再夹带其他按键。",
      highlights: [
        "轻按 Shift，就可以直接使用 macOS 已设置的输入法切换顺序，不用由本 App 重复选择输入法。",
        "豆包、微信正在组词时，按一下 Shift 也可以直接切换，下一键立即进入切换后的输入法。",
        "快速连续按 Shift 不会漏掉按键；Shift 配合字母、鼠标或其他修饰键仍按原用途工作。",
        "在千问等语音软件里按 Fn，可以由软件直接接收，不会夹带 Control 或 Option。",
        "切换结果继续由 macOS 原生浮条显示并允许直接点选其他已启用输入法。",
      ],
      previousHighlights: [
        "全局 Shift 输入法切换继续保留。",
        "打开测速窗口后，Codex 四轮连通检测会自动开始。",
        "下载、上传、延迟和抖动继续由你点击左球后才运行。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 186,
      dateText: "2026-08-14",
      title: "测速只留两个球，网络和 Codex 更清楚",
      summary: "打开测试网速，只留下两个球：左球查看上传下载与延迟抖动，右球查看 Codex 四轮连通，状态更清楚。",
      highlights: [
        "点左球查看下载、上传、延迟和抖动；测试中可以暂停，再点继续。",
        "点右球只查看 Codex 四轮连通与响应，不用再运行完整 Codex 任务。",
        "查看球的颜色就能直接分辨准备、下载、上传、稳定、波动或失败。",
        "想重测哪一项就点哪个球，另一项可以继续，不会互相等待。",
      ],
      previousHighlights: [
        "状态栏文字会自动适配深浅菜单栏，数值与单位保持清楚。",
        "从设置里安装更新时，面板开着也可以正常退出并重启。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 184,
      dateText: "2026-08-13",
      title: "状态栏文字全部统一，更新重启也更顺",
      summary: "RAM、CPU、GPU、百分比和网速数值、单位统一使用同一种前景色；从设置里安装更新时，面板开着也能正常退出并重启。",
      highlights: [
        "打开状态栏时，RAM、CPU、GPU、百分比、网速数值和单位可以直接看到同一种前景色。",
        "查看深色菜单栏时文字更清楚；设置浅色菜单栏后，文字会自动切换为深色。",
        "从设置里点击安装更新时，不用先关设置面板；确认后，应用可以正常退出并重新打开。",
      ],
      previousHighlights: [
        "网速数值和 KB/s 已经统一前景色。",
        "应用内更新继续校验签名与开发者身份，下载和安装仍由你确认。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 183,
      dateText: "2026-08-12",
      title: "网速数值和单位同色，更清楚",
      summary: "打开状态栏就能直接看到同色的网速数值和 KB/s，深色和浅色菜单栏都更协调。",
      highlights: [
        "查看网速时，数值和 KB/s 直接使用同一种前景色，不再一白一灰。",
        "打开上传或下载状态时，方向色继续保留，数值和单位可以更容易一眼看清。",
        "设置深色或浅色菜单栏时，文字会直接跟随系统外观，不用手动调整。",
      ],
      previousHighlights: [
        "深色菜单栏里的网速和内存文字恢复清晰。",
        "应用内更新改由签名 Sparkle 更新源负责，下载和安装仍会先确认。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 182,
      dateText: "2026-08-12",
      title: "菜单栏文字清楚，更新也更稳",
      summary: "深色菜单栏里的网速和内存文字恢复清晰；从这个版本开始，应用内更新交给经过签名校验的 Sparkle，下载与安装仍由你确认。",
      highlights: [
        "查看深色菜单栏时，网速、单位和内存占用不会再错误显示为黑色。",
        "查看状态栏时，文字会直接跟随菜单栏的明暗外观，不会被应用窗口主题干扰。",
        "点“检查更新”后，Sparkle 会直接校验更新源、安装包和开发者身份。",
        "选择更新时，下载和安装不会自动开始，仍会先征求你的确认。",
      ],
      previousHighlights: [
        "截图可用空格、回车或双击直接确认。",
        "菜单栏可查看系统健康，并能隐藏程序坞图标。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 181,
      dateText: "2026-08-10",
      title: "截图更顺手，菜单栏更安静",
      summary: "截图时可用空格、回车或双击直接确认；菜单栏还能查看系统健康、隐藏程序坞图标，并让 PDF 与音频按你的选择打开。这次需从官网手动覆盖安装一次，原有配置会保留。",
      highlights: [
        "框选后按空格、回车或双击即可确认，截图可以更快进入下一步。",
        "长按箭头可以选择空心、实心或圆点引导，圆角矩形让标注更自然。",
        "点击菜单栏即可查看内存压力、CPU 与交换活动；程序坞图标也可以隐藏，桌面更安静。",
        "双击剪贴板记录成功回填会轻响一声；这次点官网下载安装包并覆盖一次即可，原有快捷键和设置都会保留。",
        "在披卷或听澜里点一次“设为默认打开”，PDF 和 MP3、M4A、WAV 以后可以直接打开，也能随时恢复原应用。",
      ],
      previousHighlights: [
        "剪贴板历史可以排除 Typeless 等软件，临时复制不会反复累计。",
        "游目和披卷快捷键可以删除并随时恢复，功能本身一直保留。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 177,
      dateText: "2026-08-09",
      title: "按下什么，快捷键就记住什么",
      summary: "想用组合键，直接按；想用左右 Option、Command、Shift 或 Control 连按两下，也照着按。菜单栏还能只留下你每天会用的工具。",
      highlights: [
        "不用先懂快捷键术语：点一下录制框，按出你想要的动作，它就记住了。",
        "左右修饰键可以分别设置；双击手势认的是实体键，不会被 Caps 映射带偏。",
        "插件越来越多，菜单栏也不会越堆越长：常用入口留下，暂时不用的随手收起。",
        "收起入口不会停掉功能；应用中心、设置、更新和退出一直都在，随时找得回来。",
      ],
      previousHighlights: [
        "剪贴板历史保持紧凑单栏，双击一条就放回剪贴板并自动收起。",
        "多个文件可以整组保存，按空格即可用 Mac 原生快速查看。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 176,
      dateText: "2026-08-08",
      title: "文件变化，也只刷新一次",
      summary: "文件集合确实变化时，原生表格把重载与选中恢复作为一次原子操作，不向预览链暴露中间状态。",
      highlights: [
        "程序化重载期间暂时屏蔽 NSTableView 的中间选区通知，避免把 -1 或临时行当成用户选择。",
        "重载完成后同步最终选中项，并且只刷新一次稳定的 Quick Look 目标。",
        "状态文案或忙碌开关变化仍不会触碰文件表；真实文件变化才进入这条原子刷新路径。",
        "Build 175 已在安装版确认 Quick Look 可见、CPU 空闲和安全副本自动回收。",
      ],
      previousHighlights: [
        "连按物理右 Option 两次即可打开或收起剪贴板历史。",
        "紧凑单栏、双击回填后收起、右键安全副本操作保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 175,
      dateText: "2026-08-08",
      title: "文件表稳定，预览不再被打断",
      summary: "忙碌状态变化只更新操作能力；文件内容没有变化时，不再重载原生文件表和重置选中项。",
      highlights: [
        "准备 Quick Look 安全副本时，33 文件列表不会因状态文案变化反复 reload。",
        "原生表格只在文件集合真正变化时刷新，当前选择和正在进行的预览请求保持稳定。",
        "安全副本完成后不再因为瞬时 selection 变化被丢弃，随后进入受控 Quick Look 展示链。",
        "文件右键菜单、双击整组回填后收起和共享面板防抢占规则保持不变。",
      ],
      previousHighlights: [
        "连按物理右 Option 两次即可打开或收起剪贴板历史。",
        "紧凑单栏只在历史记录真实变化时更新，避免无效 Published 写入。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 174,
      dateText: "2026-08-08",
      title: "快速查看，准备好就出现",
      summary: "文件副本准备期间不再重复回写同一个列表选中项，完成回调可以及时显示 macOS Quick Look。",
      highlights: [
        "文件表进入忙碌状态时，列表选中项保持幂等，不再触发持续的 SwiftUI 更新循环。",
        "安全副本准备完成后会立即清除忙碌状态，并由当前文件表接管 Quick Look 面板。",
        "共享 Quick Look 面板已有其他控制者时不会被覆盖或误关；本次副本会独立释放。",
        "紧凑单栏、双击回填后收起、右键打开副本和访达定位保持不变。",
      ],
      previousHighlights: [
        "连按物理右 Option 两次即可打开或收起剪贴板历史。",
        "历史真源始终只保存在受管目录，预览和打开仅接触隔离安全副本。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 173,
      dateText: "2026-08-08",
      title: "快速查看面板，打开就在眼前",
      summary: "文件安全副本准备完成后，剪贴板历史会确定接管 macOS Quick Look 面板并显示所选文件。",
      highlights: [
        "按空格或右键“快速查看”后，即使系统没有自动交接预览控制，也会明确显示当前安全副本。",
        "预览关闭、切换记录或收起剪贴板窗口时，面板控制与临时副本会一并释放。",
        "历史真源仍不会交给 Quick Look、默认 App 或访达；外部操作只接触隔离缓存。",
        "紧凑单栏、五项筛选、缩略图和双击成功回填后收起的交互保持不变。",
      ],
      previousHighlights: [
        "连按物理右 Option 两次即可打开或收起剪贴板历史。",
        "列表只在历史记录真正变化时刷新，不再用无效更新阻塞主线程。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 172,
      dateText: "2026-08-08",
      title: "快速查看，不再卡在准备中",
      summary: "剪贴板列表只在历史记录真正变化时刷新，文件安全副本准备好后即可立即打开 Quick Look。",
      highlights: [
        "文件记录按空格或右键“快速查看”后，不再被列表的无效刷新循环阻塞在准备提示中。",
        "历史列表只观察记录数组的真实变化，并一次性更新去重次数，避免持续占用主线程。",
        "Quick Look、打开副本和访达定位继续只接触隔离缓存，不暴露或改写历史真源。",
        "双击整条记录仍会在完整回填系统剪贴板后收起面板；失败时保留原剪贴板与窗口。",
      ],
      previousHighlights: [
        "连按物理右 Option 两次即可打开或收起剪贴板历史。",
        "剪贴板保持 500pt 紧凑单栏、五项筛选和图片缩略图。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 171,
      dateText: "2026-08-08",
      title: "文件快速查看，点开就到",
      summary: "剪贴板文件的安全副本改用常数时间磁盘检查，不再卡在“正在准备快速查看副本”。",
      highlights: [
        "文件记录继续在紧凑单栏中展开；按空格或右键“快速查看”会先建立隔离副本，再交给 macOS Quick Look。",
        "磁盘余量直接读取目标卷的可用块，不再等待系统扫描所有可清理缓存；小文件预览可立即响应。",
        "右键“打开副本”和“在访达中显示副本”仍不会暴露或改写剪贴板历史真源。",
        "双击整条记录仍会在完整回填系统剪贴板后收起面板；失败时保留原剪贴板与窗口。",
      ],
      previousHighlights: [
        "连按物理右 Option 两次即可打开或收起剪贴板历史。",
        "直连网速与 Codex 响应保持两个独立测试球。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 170,
      dateText: "2026-08-08",
      title: "测速只留两个球，一眼看懂",
      summary: "直连网速显示下载和上传，Codex 响应显示完整回复要等几秒；点哪个球，就只测哪一项。",
      highlights: [
        "直连网速会连续测几秒，最后只显示下载与上传 Mbps；不再把 VPN 线路混进同一个界面。",
        "Codex 响应只发送固定短句，显示从开始到收到完整回复的秒数，不读取工作区文件。",
        "打开测速窗口不会自动消耗流量；再次点击正在测试的球即可停止本次测试。",
        "直连结果来自公共测速节点，绕过系统 HTTP(S) 代理；部分全局 VPN 仍可能影响，高速线路单次最多约 750 MB。",
      ],
      previousHighlights: [
        "连按物理右 Option 两次即可打开或收起剪贴板历史。",
        "剪贴板继续使用紧凑单栏缩略图；双击记录成功回填后收起。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 168,
      dateText: "2026-08-08",
      title: "右 Option 连按两次，剪贴板随手来",
      summary: "剪贴板历史改用实体右 Option 双击打开或收起；识别不经过软件键位映射，也不会占用 Caps。",
      highlights: [
        "连按物理右 Option 两次即可打开剪贴板历史，再连按两次收起；测试网速继续保留 Caps + T。",
        "触发直接读取原始键盘 HID 的设备和实体键位，物理左 Control 即使映射成右 Option 也不会误触发。",
        "功能快捷键的触发方式菜单可在普通组合键与右 Option 双击之间切换，重复手势会明确提示冲突。",
        "旧版默认 Caps + V 只升级一次；用户手动改键、删除或已有同手势规则时不会被强行覆盖。",
        "剪贴板继续使用紧凑单栏缩略图；双击记录成功回填后收起，内容缺失时保留原剪贴板和面板。",
      ],
      previousHighlights: [
        "普通默认快捷键和用户自定义规则可删除；固定功能保持灰色保护。",
        "文字、图片和多文件只保存在本机，重复内容合并，默认 30 天 / 1 GB。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 167,
      dateText: "2026-08-08",
      title: "剪贴板历史，更窄也更顺手",
      summary: "历史记录收成单栏缩略图；双击任意记录即可放回剪贴板，并自动收起面板。",
      highlights: [
        "普通默认快捷键和用户自定义规则现在都可删除；游目固定功能保留灰色保护，已删默认项可从列表顶部恢复。",
        "剪贴板历史从左右分栏收为紧凑单栏，默认宽度 500pt，图片直接显示有界下采样缩略图。",
        "双击文字、图片或多文件记录会先确认整条内容成功写入系统剪贴板，再收起面板并回到此前使用的 App。",
        "任一历史文件缺失时不会清空原剪贴板，也不会假装成功关闭窗口。",
        "多文件记录默认保持紧凑，按明确的展开按钮后可在行内用空格快速查看；右键继续安全打开隔离副本。",
      ],
      previousHighlights: [
        "窗口快捷键统一为第一下打开或恢复，第二下隐藏或关闭。",
        "文字、图片和多文件自动保存在本机；重复内容合并，默认 30 天 / 1 GB。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 166,
      dateText: "2026-08-08",
      title: "剪贴板历史、快捷键与测速一起收稳",
      summary: "复制过的内容随时找回，窗口快捷键统一一开一收；国内入口、VPN 吞吐与 Codex 固定任务也各自提供可信结果。",
      highlights: [
        "所有窗口快捷键统一为按一下打开、再按隐藏；快速第二下不再被时间防抖吞掉。",
        "游目选区、识别和结果窗口也支持同键第二下取消或关闭，只作用于本次任务。",
        "国内球只报绕过系统代理后的入口延迟与出口证据；大陆专用节点未就绪前不伪造 Mbps。",
        "VPN 球只在 Cloudflare 公开路由、每个上下行样本与旁路对照的代理出口全部一致时显示单连接 Mbps；路径未验证就隐藏数值。",
        "上下行先校准、再按线路速度自适应载荷，使用不可压缩随机上传和对称 body 时间窗口统计 P50 与本轮重复性。",
        "Codex 使用已签名官方 CLI、固定模型与 reasoning 在空白临时目录执行任务；触发任何工具即判无效，子进程出口未取证就明确标为未证明。",
      ],
      previousHighlights: [
        "剪贴板文件可按空格快速查看，双击或右键打开隔离副本，修改不影响历史。",
        "文字、图片和多文件自动保存在本机；重复内容合并，默认 30 天 / 1 GB，清理不碰 Finder 原文件。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 165,
      dateText: "2026-08-08",
      title: "剪贴板历史，复制过的随时找回",
      summary: "文字、图片和多个文件自动保存；重复内容合并为一条，空间上限和清理时间都可自定义。",
      highlights: [
        "应用中心新增‘剪贴板历史保存’，Caps + V 可直接打开搜索窗口。",
        "同一次复制的多个文件只占一条历史，并保存本机副本以便恢复。",
        "相同内容再次复制会移到列表顶部并累计次数，不新增重复行。",
        "默认保留 30 天、空间上限 1 GB；清理只删本应用的受管副本，不碰 Finder 原文件。",
      ],
      previousHighlights: [
        "网速单位列固定对齐，整体宽度更紧凑。",
        "软件更新完成安全替换后才退出并重开。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 164,
      dateText: "2026-08-07",
      title: "网速状态栏，更齐也更轻",
      summary: "KB/s 与 MB/s 使用同一单位列，双向箭头更轻巧，整体宽度也明显收紧。",
      highlights: [
        "上传与下载拆成右对齐数值列和固定单位列，KB/s、MB/s、GB/s 切换时保持同轴。",
        "主入口改用圆角细线双向箭头，上传与下载仍保留暖红、清蓝的直观区分。",
        "高速值改用紧凑三位格式，RAM、CPU、GPU 的安全槽位同步收窄。",
        "网速每秒刷新仍只重绘固定槽，不会推挤相邻菜单栏图标。",
      ],
      previousHighlights: [
        "软件更新完成安全替换后才退出并重开。",
        "安装或授权失败会显示真实原因和重试入口。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 163,
      dateText: "2026-08-07",
      title: "软件更新，不再回到旧版本",
      summary: "立即更新会先完成安全替换，再退出并重开；没有写入权限时由 macOS 原生确认。",
      highlights: [
        "更新前后都会复验 App 的 Bundle ID、Developer ID、团队身份和公证，只替换当前正在运行的正式 App。",
        "下载前会核对最低 macOS 版本，替换前再与 App 内声明交叉验证；不兼容时保留当前版本。",
        "新版本和回滚都通过校验后才重开；即使系统替换到一半失败，也会自动恢复旧版并保留可恢复备份。",
        "安装或授权失败会显示真实原因和“重试”，不再保留虚假的“立即更新”状态。",
        "已陷入旧版循环的电脑需先从官网手动覆盖安装这一版；之后的更新可继续在 App 内完成。",
      ],
      previousHighlights: [
        "长截图中的固定悬浮箭头不再重复入镜。",
        "实体鼠标滚轮、Space 开始／完成和连续截图保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 162,
      dateText: "2026-08-07",
      title: "长截图，固定悬浮箭头不再重复入镜",
      summary: "同一段正文改用后续画面的真实像素更新，页面上的固定下箭头不再沿长图重复出现。",
      highlights: [
        "每次接受新画面，先按页面坐标更新仍可见的旧正文，再追加真正的新尾部；不再依赖按钮颜色或形状猜测。",
        "圆形箭头、空心边框、抗锯齿与半透明阴影都随真实正文一起更新；滚到底后按钮消失，成图中也归零。",
        "正文中的相似圆形图标仍按页面位置保留，不用插值、涂抹或伪造被遮挡的文字。",
        "继续只用实体鼠标滚轮；第一次空格开始、第二次空格完成，连续第二轮截图逻辑保持不变。",
      ],
      previousHighlights: [
        "完成上一张后可直接开始下一张，不再误报目标窗口切换。",
        "已移除自动滚动按钮与合成滚轮状态机。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 161,
      dateText: "2026-08-06",
      title: "长截图，回到简单可靠的滚轮操作",
      summary: "连续截图不再误报窗口切换；只保留鼠标滚轮，并用空格开始、空格完成。",
      highlights: [
        "完成上一张后可直接开始下一张；目标只按精确 Window ID 判断，不再误用前台 App 状态。",
        "移除自动滚动按钮、合成滚轮事件及其重试状态机，长截图只旁听真实鼠标滚轮。",
        "框选后按空格开始，采集中再按一次空格等同点击“完成”；Chrome 不会同时收到该空格。",
        "宿主编辑器或同进程另一窗口真正覆盖选区时仍会拒绝，避免截到错误窗口。",
      ],
      previousHighlights: [
        "截图、滚动、预览和完成共用精确窗口的实时帧时间线。",
        "完成时有限排空，尾部不完整会明确提示。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 160,
      dateText: "2026-08-06",
      title: "长截图，实时滚动链路重做",
      summary: "截图、滚动、预览和完成改为同一条实时帧时间线，页面移动后不再只滚动却不出图。",
      highlights: [
        "精确捕获所选窗口的 ScreenCaptureKit 完整帧；第一张实时帧是唯一拼接起点。",
        "快滚按时间顺序补齐中间画面，右侧预览与最终图片只显示同一条已接受时间线。",
        "蓝框和预览不接管鼠标；物理滚轮保持原生，自动滚动可由手动滚轮接管。",
        "完成时排空冻结的有限帧集合；尾部未对齐或达到安全长度上限会明确提示结果不完整。",
      ],
      previousHighlights: [
        "卸载失败时可直接在 Finder 中定位目标 App。",
        "失败提示改为窗口级异步 Sheet，不再阻断游目选区。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 159,
      dateText: "2026-08-06",
      title: "卸载遇阻，直接回到应用程序",
      summary: "遇到带登录项或系统扩展、无法安全彻底卸载的 App，可直接在 Finder 中定位并自行移到废纸篓。",
      highlights: [
        "失败提示新增‘在“应用程序”中显示’，点击后由 Finder 原生选中目标 App。",
        "提示会明确右键选择‘移到废纸篓’，并说明这只移动主 App，辅助组件仍可能要用官方卸载器清理。",
        "失败提示改为窗口级异步 Sheet；提示留在画面时，游目的截图选区仍可正常接收键盘和鼠标。",
      ],
      previousHighlights: [
        "长截图改用精确目标窗口的 ScreenCaptureKit 连续帧流。",
        "快滚时按最旧优先补齐仍有重叠的中间画面。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 158,
      dateText: "2026-08-06",
      title: "长截图，改用实时帧流",
      summary: "截取、拼接与预览共用连续的 ScreenCaptureKit 画面，页面滚动后不再停在第一段。",
      highlights: [
        "第一张完整实时画面成为唯一拼接起点，不再混用框选时的冻结图和运行时截图。",
        "精确绑定所选窗口，以每秒 30 帧进入八帧有界队列；快滚时按顺序补齐仍有重叠的中间画面。",
        "物理滚轮只被旁听，蓝框和预览不接管鼠标；宿主滚轮引擎在会话期间完整停止。",
        "完成时先冻结有限帧序号再排空，自动滚动只接受事件之后且已经稳定的画面。",
      ],
      previousHighlights: [
        "框选后直接点‘开始长截图’。",
        "自动滚动成功停下后会直接生成结果。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 157,
      dateText: "2026-08-06",
      title: "长截图，快滚也能跟上",
      summary: "快速滚轮会保留中间画面，右侧预览不再反过来堵住拼接。",
      highlights: [
        "手动快速滚动时最多保留八张中间画面，避免只剩最后一屏、前后失去重叠。",
        "右侧预览先立即显示首帧，后续缩略图等拼接队列排空再更新，不再抢占截图工作。",
        "取消或重开长截图会废止上一轮未完成的像素任务，连续重试不会被旧队列拖慢。",
        "自动滚动和完成按钮改为固定高对比样式，并支持在非激活控制条上第一次点击就执行。",
      ],
      previousHighlights: [
        "框选后直接点‘开始长截图’。",
        "自动滚动成功停下后会直接生成结果。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 156,
      dateText: "2026-08-05",
      title: "长截图，开始与出图都说清楚",
      summary: "框选后直接点‘开始长截图’；自动滚动成功停下后会自动生成结果。",
      highlights: [
        "选区内新增可见的‘开始长截图’按钮，空格键仍可作为辅助操作。",
        "点击开始前会拦住滚轮，不再出现页面已滚动、截图却尚未启动的假状态。",
        "自动滚动在成功拼接且多点连续静止后直接补抓末屏并打开结果，不再还要另点一次完成。",
        "蓝色采集边界只在首帧、拼接器和监听就绪后出现；最近长截图状态会以脱敏环形日志保留。",
      ],
      previousHighlights: [
        "低纹理、重复模块与悬浮控件的拼接更稳定。",
        "42 帧真实浏览器回放与页面高度精确一致。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 155,
      dateText: "2026-08-05",
      title: "长截图，完整拼到页底",
      summary: "重做低纹理长页的对齐与悬浮控件处理，避免页面明明移动却中途停止。",
      highlights: [
        "大面积纯色、重复模块与小段文字并存时，改用分布式多区域证据确认位移。",
        "页面右下角悬浮按钮不再被误当成整行底栏，也不会持续擦除它出现前或消失后的正文。",
        "对齐失败、页面停止、失焦与用户接管现在分别记录，不再用一个模糊结果掩盖中途停止。",
        "42 帧真实浏览器回放逐段精确匹配，成品高度与 12920px 页面完全一致。",
      ],
      previousHighlights: [
        "物理滚轮在长截图期间保持原生直通。",
        "新增“自动滚动直到滚动到底为止”。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 154,
      dateText: "2026-08-05",
      title: "长截图，滚轮不再失灵",
      summary: "长截图期间让物理滚轮原生直通，并加入可人工确认、可继续探测的自动滚动到底按钮。",
      highlights: [
        "修复长截图启动时滚轮监听被错误重新启用，导致网页偶发完全滚不动的问题。",
        "控制条上的滚轮会继续转发给原网页，不再被“完成”按钮所在面板截住。",
        "新增“自动滚动直到滚动到底为止”，小步滚动、逐段确认，页面静止后仍可继续探测。",
        "每次取帧都绑定原目标窗口；失焦立即取消，物理滚轮、导航键或滚动条拖动可随时接管。",
      ],
      previousHighlights: [
        "App 与官网统一使用“查看更新记录”。",
        "主窗口标题旁可直接进入新版本更新。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 152,
      dateText: "2026-08-05",
      title: "更新记录，只留一个入口",
      summary: "App 与官网现在共用同一张更新记录，不再各开一页。",
      highlights: [
        "更新完成弹窗统一显示“查看更新记录”，直接进入当前官网的更新记录页。",
        "旧更新日志页面不再维护第二份内容，老版本 App 与历史书签会自动跳到新页面。",
        "官网顶部、下载区、页脚与支持页共用同一个名称和地址。",
        "更新检查、下载、校验、安装与发布框架保持不变。",
      ],
      previousHighlights: [
        "发现新版本时，主窗口标题旁会直接出现更新入口。",
        "网速数字变化不再推挤菜单栏图标。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 151,
      dateText: "2026-08-05",
      title: "有新版本，抬眼就能看到",
      summary: "发现可安装的新版本时，主窗口标题旁会直接出现“更新到新版本”。",
      highlights: [
        "更新提醒只在真正检测到更高构建号且当前许可可更新时出现。",
        "入口紧贴主窗口标题，不需要小白用户先进入“关于”寻找。",
        "点击后继续复用原有的下载、SHA、App 身份、Developer ID、公证和 Gatekeeper 校验链。",
        "未发现新版本时不显示按钮，标题栏保持安静。",
      ],
      previousHighlights: [
        "网速数字变化不再推挤菜单栏图标。",
        "RAM、CPU、GPU 与音量显示共用稳定外框。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 150,
      dateText: "2026-08-05",
      title: "网速变化，菜单栏不再跟着晃",
      summary: "网速与系统占用只在固定位置更新，数字位数变化不再推挤旁边的菜单栏图标。",
      highlights: [
        "上传、下载从个位数变成三位数或 MB/s 时，状态项保持同一宽度。",
        "RAM、CPU、GPU 从一位数变成 100% 时，也不会让相邻图标左右移动。",
        "音量百分比短暂显示时复用原有位置，不再额外改变菜单栏宽度。",
        "菜单、测速、采样频率、快捷操作和插件架构保持不变。",
      ],
      previousHighlights: [
        "系统深色时，纸白界面仍保持清楚。",
        "功能快捷键分类使用显式高对比按钮。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 149,
      dateText: "2026-08-04",
      title: "系统深色时，界面也保持清楚",
      summary: "当前纸白视觉统一使用 Aqua 亮色外观，不再让系统深色模式把固定墨色文字压进黑底。",
      highlights: [
        "修复关于页、应用中心和独立窗口在系统深色模式下出现黑字压黑底的问题。",
        "功能快捷键的分类行改为显式高对比按钮，未选分类不再白字隐入白底。",
        "关于页与顶部导航同时改用语义文字色，后续扩展完整暗色视觉时不会再从这里倒退。",
        "许可卡、按钮品牌色和现有功能逻辑不变。",
      ],
      previousHighlights: [
        "14 天全功能免费试用正式开放。",
        "打开主窗口先进入应用中心，并给出三条首次结果路线。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 148,
      dateText: "2026-08-04",
      title: "第一次打开，先完成一个真实结果",
      summary: "14 天全功能免费试用正式开放；主窗口先进入应用中心，并给出三条可以直接动手的起步路线。",
      highlights: [
        "新安装首次联网自动开始 14 天全功能免费试用：免邮箱、免密码、免绑卡，试用期内现有功能全部开放。",
        "打开主窗口先看到应用中心，不再先掉进密集的快捷键配置表。",
        "新增‘第一次先完成一个结果’：看懂屏幕外文、快速找到 App、少做重复动作，点一下就到对应入口。",
        "功能快捷键正式纳入应用中心，App 与官网统一为 15 项能力。",
        "试用期间可直接购买；主播、网红和活动来源可随安全付款订单回传，只用于统计，不参与许可权益判断。",
      ],
      previousHighlights: [
        "更新校验不再依赖 Xcode 工具，异常会超时并保留旧版。",
        "三项系统权限全开后只重启一次并回到正常界面。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 147,
      dateText: "2026-08-02",
      title: "立即更新不再卡在校验",
      summary: "去掉顾客电脑上的 Xcode 工具依赖，校验异常会超时退出并保留旧版。",
      highlights: [
        "更新器只使用 macOS 自带的签名与 Gatekeeper 校验，普通 Mac 无需安装 Xcode 或命令行工具。",
        "外部安全校验加入硬超时；失败时显示原因，不会无限留在‘正在校验’。",
        "安装前完成公证与 Gatekeeper 验证，替换后再核对 Developer ID、Team ID 和指定要求；失败仍自动恢复旧版。",
        "游目与披卷不再各自堆叠快捷键设置；统一跳转到主窗口‘功能快捷键’，内置项不可删除。",
      ],
      previousHighlights: [
        "三项系统权限全开后只重启一次并回到正常界面。",
        "旧许可后台读取不再被过时钥匙串标志误伤。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 146,
      dateText: "2026-08-02",
      title: "权限开完，只重启一次就回到正常",
      summary: "补齐本机屏幕录制提示识别；系统提示与全线全开共用一次性重启，失败只留手动出口。",
      highlights: [
        "识别 macOS 本机实际提示“将无法录制屏幕内容，直至退出”，不再错误停留在拖入或双击卡。",
        "系统重开提示与三项权限全开共用同一个防重闸门；谁先触发都只会退出旧进程一次。",
        "自动重启或外部接力超时失败时立即关闭抖动引导，保存当前进度，只提示退出后从“应用程序”手动打开。",
        "不同新 PID 验证三项权限后直接清理授权会话并回到正常界面，不再多弹一个完成页。",
      ],
      previousHighlights: [
        "旧许可后台读取不再被过时钥匙串标志误伤。",
        "授权与恢复弹层允许 macOS 正常终止旧进程。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 145,
      dateText: "2026-08-02",
      title: "旧许可直接续上，系统重开不再卡住",
      summary: "去掉会误伤旧钥匙串的重复禁止标志；授权与更新弹层不再阻挡 macOS 退出并重新打开。",
      highlights: [
        "旧许可的后台读取只使用现代 LAContext 无交互约束，不再叠加会把可读旧条目误报为 -25308 的过时 UI-skip 标志。",
        "授权向导弹层明确允许系统终止；macOS 点“退出并重新打开”时，会先记录当前步骤，再由新 PID 继续下一项。",
        "更新说明与购买邮箱恢复弹层也不会再挡住正常退出，安装替换和手动重开都能走同一条进程接力。",
        "build 143 的半份许可仍先保留可恢复备份；只有完整安全仓跨多次重启持续激活后才清理备份。",
      ],
      previousHighlights: [
        "旧许可整包迁移后才允许单字段更新。",
        "购买邮箱恢复使用独立、可访问的前台引导框。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 144,
      dateText: "2026-08-02",
      title: "许可跨多少次重启都能续上",
      summary: "旧许可先整包迁入新版安全仓，再允许更新时间；恢复表单改为独立前台引导框。",
      highlights: [
        "首次读到旧许可时，设备身份、登录状态、签名许可与计时字段必须完整读完，才会一次性迁入 Data Protection Keychain。",
        "后续单字段更新只能在完整安全仓上追加，不会再制造第一次重启已激活、第二次重启又失效的半份许可。",
        "购买邮箱恢复改为独立弹出的前台引导框，邮箱、验证码和操作按钮都有明确的键盘与辅助功能身份。",
        "正式安装替换按精确 App 路径和进程身份正常退出；新 PID 启动后继续读取同一份安全许可。",
      ],
      previousHighlights: [
        "三项系统权限继续按 1/3、2/3、3/3 在前台逐步引导。",
        "系统提示退出并重新打开时，授权进度仍由新进程接力。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 143,
      dateText: "2026-08-02",
      title: "小白授权和许可恢复从头走到底",
      summary: "三项权限逐步前台引导；购买邮箱可直接恢复许可，重启也能继续生效。",
      highlights: [
        "辅助功能、屏幕录制和输入监控按 1/3、2/3、3/3 展示当前步骤，每换一步前台授权卡只抖一次。",
        "列表里没有本 App 时，可拖入完整安装版，或双击授权卡向 macOS 发起官方登记请求。",
        "系统提示‘退出并重新打开’时保留授权进度；不同的新进程启动后自动继续下一项。",
        "收起授权中心不再取消接力，权限开关已开与新进程验收分开记录。",
        "旧钥匙串失读时，购买邮箱是恢复主路；旧记录尝试只走 macOS 安全接口，不会强制锁定整个登录钥匙串。",
        "许可写入 Data Protection Keychain；只创建、不覆盖，并以代际标记和静默回读作为激活条件。",
      ],
      previousHighlights: [
        "旧许可记录保留原位，迁移失败或用户取消都不会删除、覆盖或放行权益。",
        "14 天全功能自动试用保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 142,
      dateText: "2026-08-02",
      title: "钥匙串锁住也有正确恢复路线",
      summary: "本机试用与许可读取失败时，可由 macOS 系统解锁并立即恢复。",
      highlights: [
        "‘重新读取’改为真正的‘解锁并恢复许可’，用户点击后由 macOS 系统窗口处理钥匙串密码。",
        "软件不读取、不保存钥匙串密码，失败或取消也不删除现有试用与许可记录。",
        "启动和自动重试仍保持静默，只有用户明确点击时才允许系统弹出解锁界面。",
        "许可页去掉重复红色报错和无关付款提示，分组名改为‘试用与许可’。",
      ],
      previousHighlights: [
        "新 Mac 无需 mpv 即可播放 MP3、M4A 和 WAV。",
        "14 天全功能自动试用保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 141,
      dateText: "2026-08-02",
      title: "新电脑也能直接播放",
      summary: "常用音频改用 macOS 原生播放，mpv 从必装插件降为扩展格式的可选后端。",
      highlights: [
        "全新 Mac 不安装 Homebrew 或 mpv，也能直接打开播放器并播放 MP3、M4A、WAV。",
        "播放、暂停、进度跳转、音量和历史进度统一接入原生 AVFoundation 引擎。",
        "FLAC、OGG、Opus 与视频仍走可选扩展后端；缺少时只提示当前格式，不再判定整个播放器不可用。",
        "应用中心与播放器标题会显示真实能力：原生音频始终可用，扩展媒体按本机环境显示。",
      ],
      previousHighlights: [
        "选哪读哪已支持原生缩放、最小化、全屏和三档阅读字号。",
        "14 天全功能自动试用保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 140,
      dateText: "2026-08-02",
      title: "选哪读哪成为真正的阅读器",
      summary: "正文优先、字号可调，并使用原生可缩放与全屏窗口承载朗读。",
      highlights: [
        "窗口改用 macOS 原生标题栏，可自由缩放、最小化并进入全屏。",
        "加入小、中、大三档阅读字号，同时支持 ⌘+、⌘- 和 ⌘0。",
        "全屏时正文仍保持舒适行宽，不会横向铺满；手动滚动仍会暂停自动跟随。",
        "声音、倍速、进度、逐词高亮和空格暂停继续使用原有朗读状态，不另造第二套播放器。",
      ],
      previousHighlights: [
        "永不睡眠按状态、时长、自定义和屏幕策略重新排好层级。",
        "14 天全功能自动试用保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 139,
      dateText: "2026-08-02",
      title: "永不睡眠界面重新排好了",
      summary: "按当前 VI 重做状态、时长和屏幕策略的操作层级，去掉重复和漂浮控件。",
      highlights: [
        "当前状态、预设时长、自定义时长和屏幕策略改为四层清晰顺序。",
        "独立窗口只保留 macOS 原生关闭键，不再重复显示大号关闭按钮。",
        "六个常用时长统一为三列栅格；自定义加减和开始操作收拢在同一行。",
        "界面使用纸白、墨色和精确小龙哥紫，不再使用蓝绿玻璃渐变。",
      ],
      previousHighlights: [
        "菜单常用入口、功能快捷键完整分类与 PDF 共享设置已经接通。",
        "新用户首次安装的 14 天全功能自动试用保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 138,
      dateText: "2026-08-01",
      title: "常用入口与快捷键一处看全",
      summary: "补齐菜单常用入口、独立永不睡眠窗口和快捷键完整分类，并准备好 14 天全功能试用。",
      highlights: [
        "菜单新增输入法管理、测试网速、永不睡眠、启动器和查看快捷键；有快捷键的入口直接显示实际按键。",
        "醒／眠左键切换，右键打开独立永不睡眠窗口；查看快捷键直达首页功能快捷键。",
        "截图、PDF、工具、窗口、软件、系统和脚本快捷键统一分类；披卷 PDF 与原窗口共用同一份设置。",
        "新用户首次安装自动开启 14 天全功能免费试用，无需邮箱、密码、付款方式，也不按 Pro 功能拆分。",
      ],
      previousHighlights: [
        "现有用户升级后自动补回缺失的游目默认快捷键，已有自定义规则不覆盖。",
        "快速截图、标注、长截图、钉图、OCR、朗读和翻译都在菜单中显示实际快捷键。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 137,
      dateText: "2026-08-01",
      title: "菜单直接看见快捷键",
      summary: "补回游目默认快捷键，并把菜单里的等级标签换成真正有用的按键提示。",
      highlights: [
        "现有用户升级后自动补回缺失的 7 条游目默认快捷键，已有自定义规则不覆盖。",
        "快速截图、标注、长截图、钉图、OCR、朗读和翻译都在菜单中显示实际快捷键。",
        "菜单移除 Pro 尾巴；能力权限仍在执行时按许可判断，不占用日常操作文案。",
      ],
      previousHighlights: [
        "辅助功能、屏幕录制和输入监控按顺序自动推进，只保留一个主按钮。",
        "升级后先复用已有授权；只有新增或丢失的权限才会再次引导。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 136,
      dateText: "2026-08-01",
      title: "三项权限一次走完",
      summary: "把游目屏幕录制并入统一授权中心，首次安装和升级后都由软件自动判断下一步。",
      highlights: [
        "辅助功能、屏幕录制和输入监控按顺序自动推进，只保留一个主按钮。",
        "升级后先复用已有授权；只有新增或丢失的权限才会再次引导。",
        "截图权限缺失不会拖停 Caps、快捷短语等已经具备权限的功能。",
      ],
      previousHighlights: [
        "打开游目会进入完整设置窗口，截图、OCR、长截图与定图调用真实功能。",
        "打开披卷 PDF 会进入原生阅读窗口。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 135,
      dateText: "2026-08-01",
      title: "游目与披卷真正装上船",
      summary: "修复正式包漏编原生模块的问题，应用中心里的游目、截图和披卷 PDF 恢复可用。",
      highlights: [
        "打开游目会进入完整设置窗口，截图、OCR、长截图与定图调用真实功能。",
        "打开披卷 PDF 会进入原生阅读窗口，不再停留在无响应的应用中心按钮。",
        "正式版与开发版统一使用同一条模块化构建链，缺少任一模块将直接禁止出包。",
      ],
      previousHighlights: [
        "全局输入权改为事件驱动，只在必要时检查稳定版进程。",
        "启动器搜索与菜单栏响应更轻快。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 134,
      dateText: "2026-08-01",
      title: "常驻更轻，搜索更快",
      summary: "减少无效轮询和重复计算，让后台常驻、启动器搜索与菜单栏响应更利落。",
      highlights: [
        "全局输入权改为事件驱动，只在必要时检查稳定版进程。",
        "启动器一次建立历史与运行状态索引，不再为每个候选反复扫描。",
        "诊断关闭时不再构造日志字段；GPU 采样移出菜单栏主线程。",
      ],
      previousHighlights: [
        "点击网速区域即可看到截图、OCR、快捷短语、测速和应用中心。",
        "菜单与独立窗口第一次点击就抵达正确目标。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 133,
      dateText: "2026-08-01",
      title: "菜单与窗口一步到位",
      summary: "点击网速直接展开快捷菜单，菜单跳转和启动器收起也更利落。",
      highlights: [
        "点击网速区域即可看到截图、OCR、快捷短语、测速和应用中心。",
        "移除菜单顶部没有动作的灰色“游目”，打开后直接进入可执行功能。",
        "菜单切换会先收起上一个独立窗口，第一次点击就显示正确目标。",
      ],
      previousHighlights: [
        "Caps + Space 再按一次会立即收起启动器，不再被打开防抖拖慢。",
        "自动检查更新失败保持安静；开发版关于页也不再显示黄色故障框。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 132,
      dateText: "2026-07-31",
      title: "网速成为唯一主入口",
      summary: "菜单栏少占一格：左键网速打开主窗口，右键查看统一快捷操作。",
      highlights: [
        "移除原四宫格主状态项和容易误导的“打开游目窗口”。",
        "网速入口默认常驻；许可恢复中也不会把设置与退出入口一并隐藏。",
      ],
      previousHighlights: [
        "右键菜单在网速辅助进程内原生展开，游目动作执行前不会抢走原前台 App。",
        "鼠标音量百分比改由同一网速入口短暂显示，不增加新的菜单栏占位。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 131,
      dateText: "2026-07-31",
      title: "状态栏只留常用动作",
      summary: "快捷短语现在每次都能准确打开；菜单换成短语、测速和进程等常用工具。",
      highlights: [
        "快捷短语直接定位到应用中心详情，窗口在前台时也不会反向收起。",
        "移除 Mac 哲学标题、App 启动器、权限和开机启动等低频状态栏项。",
      ],
      previousHighlights: [
        "永不睡眠状态项新装默认显示，仍尊重用户手动隐藏。",
        "“眠”状态不再被后台响应活动偷偷阻止系统睡眠；不锁屏、不进屏保默认关闭。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 130,
      dateText: "2026-07-31",
      title: "测速同时看上传和下载",
      summary: "国内网络现在同时显示下载、上传参考，并保留常用国内入口的连接判断。",
      highlights: [
        "下载和上传串行测试，球面与结果卡同时显示两个 Mbps。",
        "上传失败显示未完成，重复测速、关窗或停用会取消旧任务。",
      ],
      previousHighlights: [
        "整次国内测试计划数据约 22.2 MB（不含协议开销），上传只发送内存生成的空白数据。",
        "带宽数值明确标为 Cloudflare 公共节点参考，不冒充大陆服务器实测。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 129,
      dateText: "2026-07-31",
      title: "授权精灵全程不消失",
      summary: "同一张浮动卡会跟随授权进度变化；权限齐全后留在屏幕上，整卡可点击重启。",
      highlights: [
        "拖入列表、开启开关、权限齐全和重新打开都在原位给出下一步。",
        "系统设置关闭或切回 App 后，最终重启卡仍会固定留在当前屏幕底部。",
      ],
      previousHighlights: [
        "苹果原生重启提示继续保留为系统兜底，软件不点击系统开关或弹窗。",
        "正常授权和一键清除后的重启统一走可靠退出路径，再按精确安装路径重开。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 124,
      dateText: "2026-07-31",
      title: "系统重启提示识别补全",
      summary: "输入监控提示无论显示为窗口还是系统表单，软件都会识别并自行退出重开。",
      highlights: [
        "补齐 macOS 26 把重启提示暴露为焦点表单或 Sheet 时的只读识别。",
        "继续要求本 App 名、键盘输入提示和重启动作同时命中，避免把普通列表误判为完成。",
      ],
      previousHighlights: [
        "软件只正常退出自身，接力器仍等待旧主 PID 消失后按精确安装路径重开。",
        "识别失败仍保留苹果原生按钮，不点击系统开关或修改 TCC。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 123,
      dateText: "2026-07-31",
      title: "输入监控授权少点一次",
      summary: "打开输入监控开关后，软件会识别苹果的重启提示并自行退出重开，不再要求用户再点一次系统按钮。",
      highlights: [
        "只读识别系统设置对本 App 的输入监控重启提示，不点击系统开关或弹窗。",
        "旧主进程正常退出后，由临时接力器按应用程序中的精确路径重新打开。",
      ],
      previousHighlights: [
        "识别不到系统提示时仍保留苹果原有“退出并重新打开”按钮作安全兜底。",
        "正常授权不清权限；一键修复仍只在用户二次确认后处理本 App 两项记录。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 122,
      dateText: "2026-07-31",
      title: "权限修复真正一键收口",
      summary: "授权完成后自动重新打开软件；异常时一键修复旧记录，Caps 也会区分权限与许可问题。",
      highlights: [
        "正常拖拽不再同步清权限，授权卡上移更流畅。",
        "一键修复仅在用户确认后清理本 App 旧记录，然后自动重启并按顺序引导。",
      ],
      previousHighlights: [
        "权限由不完整变为完整时，只自动重启一次，并恢复授权结果页。",
        "钥匙串暂不可用时可自动或手动重读许可；Caps 直接给出恢复入口。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 121,
      dateText: "2026-07-31",
      title: "权限入口不再藏起来",
      summary: "设置页常驻系统权限与一键清除入口；Caps 核心键缺权限时会直接显示“需要授权”，并可进入检测与修复。",
      highlights: [
        "无论权限是否完整，关于／设置页都能随时检测、管理或一键清除本 App 权限。",
        "Caps 列表优先显示真实权限缺口，详情页始终保留检测与管理权限按钮。",
      ],
      previousHighlights: [
        "重启接力改为优先按当前安装路径重新打开，避免 LaunchServices 只认旧登记。",
        "一键清除仍需明确确认，且只处理本 App 的辅助功能和输入监控。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 120,
      dateText: "2026-07-30",
      title: "权限异常，可以一键重新来过",
      summary: "授权中心新增“一键清除权限”，只清本 App 的辅助功能与输入监控，随后自动重启并重新引导授权。",
      highlights: [
        "显式确认后才执行，不影响其他 App 或其他系统权限。",
        "清除成功后复用可见重启链，并按辅助功能、输入监控顺序重新引导。",
      ],
      previousHighlights: [
        "正常首次授权保持原样，不会自动清除已有权限。",
        "系统开关仍由用户亲手打开，App 不模拟点击或绕过 macOS 安全机制。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 119,
      dateText: "2026-07-30",
      title: "这版让权限重启真正回到眼前",
      summary: "权限重启不仅更换主进程，还会恢复授权结果页、重新显示主窗口并主动回到前台。",
      highlights: [
        "接力器会在旧主进程退出后打开 App，并再次触发窗口恢复，避免只在后台启动。",
        "新进程会回读权限并显示“软件已重新打开”的结果；进程、窗口和前台状态分别记录。",
      ],
      previousHighlights: [
        "重启请求只在授权流程内保存十分钟，过期后不会在普通启动时抢前台。",
        "正式许可状态与系统权限继续分开显示，重启不会把未激活许可冒充成功。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 118,
      dateText: "2026-07-30",
      title: "这版补上不会重置的 7 天试用",
      summary: "新用户用邮箱验证码开始 7 天全功能试用；无需密码或绑卡，重装后只会恢复原来的剩余时间。",
      highlights: [
        "试用时间和权益由服务端签名，本机删除许可数据不能重新获得 7 天。",
        "同一次开机内可离线使用到固定结束时间；重启 Mac 后需短暂联网恢复可信计时。",
      ],
      previousHighlights: [
        "已购买用户始终优先恢复买断许可，试用不会覆盖或缩短已购权益。",
        "App 只保存随机设备 ID 和签名凭证，不采集序列号、Apple ID 或硬件指纹。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 117,
      dateText: "2026-07-30",
      title: "这版修好权限旧项与自动重启",
      summary: "拖动授权卡时会先精确清掉当前 App 的旧权限项，再添加当前安装版；授权重启会等旧主进程真正退出后再打开。",
      highlights: [
        "清理动作等同于先点系统列表减号，只作用于当前仍未生效的辅助功能或输入监控，不碰其他 App 和已生效权限。",
        "系统提示退出重开、授权完成重启和监听恢复重启统一等待旧主 PID 消失，避免新实例撞上单实例锁后退出。",
      ],
      previousHighlights: [
        "用户仍只需要拖动授权卡并亲手打开系统开关，App 不模拟点击系统开关。",
        "五分钟接力超时后自动清理标记，不形成长期后台进程或重复启动。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 116,
      dateText: "2026-07-30",
      title: "这一版补上正式发行保护",
      summary: "正式包开始裁剪可读符号与开发路径，并把 Pro 许可从界面提示落实到每次功能执行。",
      highlights: [
        "快捷键、短语、启动器、Caps、输入法、鼠标、睡眠、进程、网速和播放器统一在执行层核验签名许可。",
        "许可加载失败、设备或权益不匹配时安全停用后台引擎；购买、恢复、设置、停止、退出和彻底卸载始终可用。",
      ],
      previousHighlights: [
        "正式构建使用整模块优化、dead strip 和符号裁剪；私有 dSYM 留在本机，不进入 App、DMG 或 ZIP。",
        "软件更新按签名凭证中的更新截止日核对目标版本发布日期，已购旧版本不会因自然过期而失效。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 115,
      dateText: "2026-07-30",
      title: "这版把卸载收成一次确认",
      summary: "启动器里的卸载现在只有一次不可撤销警告；确认后直接结束目标 App，并永久删除主程序与已确认的专属数据。",
      highlights: [
        "运行中的目标 App 与内嵌辅助进程会被直接强制结束，不再出现二次强退确认。",
        "卸载不再经过废纸篓，也没有清单页、恢复页或成功弹层。",
      ],
      previousHighlights: [
        "只处理精确身份和明确归属的 App 数据；共享容器、用户文档与系统扩展继续保留。",
        "受 macOS 保护的对象最多触发一次系统管理员认证；App 不保存密码。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 114,
      dateText: "2026-07-29",
      title: "这一版，把激活变成一场点亮典礼",
      summary: "首次激活与新 Mac 恢复现在会进入独立的 Pro 点亮仪式：黑曜石展厅、珐琅绿 Caps、原创品牌音乐，以及可保存的纪念卡。",
      highlights: [
        "首次点亮与欢迎回来使用两套情绪文案；动画遵循 macOS 减少动态效果与减少透明度设置。",
        "品牌启动音由 App 离线确定性合成，不使用外部采样；纪念卡不含邮箱、设备或许可证信息。",
      ],
      previousHighlights: [
        "同一激活凭证只自动展示一次；启动读取、后台同步和更新重启不会重复触发。",
        "已激活用户可在 Pro 许可页随时重看仪式，并导出 1600×900 PNG。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 112,
      dateText: "2026-07-29",
      title: "这版修好系统设置要求的退出重开",
      summary: "系统设置点击“退出并重新打开”后，主 App 现在会明确允许系统终止，再由系统或授权接力器重新打开。",
      highlights: [
        "退出验收改为旧主进程 PID 消失、新主进程 PID 出现，不再把网速状态栏重载误认为 App 重启。",
        "继续保留五分钟有界接力；系统已经重新打开时，单实例保护会阻止重复启动。",
      ],
      previousHighlights: [
        "输入监控授权仍由用户亲手开启，不模拟系统开关。",
        "授权流程完成前不发布，必须经过真实缺权限重测。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 111,
      dateText: "2026-07-29",
      title: "这版补上系统退出后的自动重开",
      summary: "输入监控让 macOS 先退出 App 时，外部接力器仍会从“应用程序”自动重新打开正式版。",
      highlights: [
        "接力器只等待当前 App 退出，最长五分钟；完成重开后立即自行结束。",
        "用户关闭授权流程会取消接力，不会把以后正常退出误判为需要重开。",
      ],
      previousHighlights: [
        "选择系统提示中的“退出并重新打开”或“以后”，授权流程都能收口为重启本 App。",
        "不重启电脑，不模拟系统开关，不改变其他 App 权限。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 110,
      dateText: "2026-07-29",
      title: "这版把授权卡真正放进系统设置",
      summary: "点击“立即授权”后直接打开当前权限页，并在系统设置底部显示可整卡拖入、会抖动的授权引导卡。",
      highlights: [
        "授权中心移除辅助功能和输入监控的编号菜单，只保留一个主动作。",
        "抖动的是 App 自己的拖拽卡，不是 macOS 系统行；整张卡指向“应用程序”中的当前安装版。",
      ],
      previousHighlights: [
        "当前权限生效后自动推进下一项，全部完成后隐藏授权卡并自动重启软件。",
        "旧辅助功能记录只按当前 Bundle ID 精确清理，不影响其他 App 或其他权限。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 108,
      dateText: "2026-07-29",
      title: "这版把授权真正收成一次操作",
      summary: "第一次点击不再清理权限或中途重启；软件直接按顺序打开两项系统设置，全部开启后只重启本 App 一次。",
      highlights: [
        "授权页改成清楚的两步只读进度，用户仍然只操作一个“立即授权”按钮。",
        "辅助功能生效后自动推进输入监控，无需返回软件重新检测。",
      ],
      previousHighlights: [
        "正常首次授权不执行 TCC reset；已开启权限和其他 App 权限保持不变。",
        "系统设置开关仍由用户亲手开启，全部完成后自动退出并重新打开“小龙哥Mac哲学”。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 107,
      dateText: "2026-07-29",
      title: "这版让授权真正只剩系统开关",
      summary: "点击“立即授权”后不再先弹辅助功能确认框，软件直接打开正确的系统设置页面；两项完成后自动重启软件。",
      highlights: [
        "辅助功能与输入监控按顺序直接打开，不再要求用户先处理额外的 macOS 确认菜单。",
        "授权完成后的“重启”统一明确为自动退出并重新打开“小龙哥Mac哲学”，不是重启电脑。",
      ],
      previousHighlights: [
        "系统安全开关仍必须由用户亲手开启；App 不绕过 macOS 权限机制。",
        "macOS 不保证第三方 App 能让设置列表中的某一行持续抖动，产品以直接落到正确页面和状态检测为准。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 106,
      dateText: "2026-07-29",
      title: "这版把系统授权收成一个入口",
      summary: "插件、快捷键、设置和菜单栏不再分别要求用户判断辅助功能、输入监控或重新检测；统一交给一个“立即授权”入口自动处理。",
      highlights: [
        "用户只需要点一次“立即授权”，软件实时判断缺少哪项，并按正确顺序打开 macOS 授权引导。",
        "已生效权限、其他 App 权限和现有钥匙串数据保持不变，系统开关仍由用户亲手开启。",
      ],
      previousHighlights: [
        "Caps、鼠标滚动、鼠标音量、窗口切换、快捷键警告和设置页全部回到同一个授权中心。",
        "本机候选继续使用稳定签名身份；身份异常时钥匙串静默降级，不弹密码框、不覆盖旧数据。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 105,
      dateText: "2026-07-29",
      title: "这版不再反复索要钥匙串密码",
      summary: "本机候选恢复稳定签名身份；许可证钥匙串遇到旧身份限制时静默降级，不再让四个许可项连续弹出密码框。",
      highlights: [
        "后续本机版本默认沿用同一签名要求，辅助功能、输入监控和钥匙串不再因每次构建哈希变化而被当成新 App。",
        "钥匙串先检查项目是否存在，再以禁止交互方式读取；无权读取时保持原数据不变，也不创建新设备身份覆盖旧值。",
      ],
      previousHighlights: [
        "设备 ID、登录会话、签名许可和试用起点仍保存在原钥匙串服务，不降低许可安全边界。",
        "正式发布仍必须单独完成 Developer ID 签名、公证、安装与线上回拉；本候选没有发布。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 99,
      dateText: "2026-07-28",
      title: "这版正式接通了金数据购买",
      summary: "Mac 哲学 Pro 的付款入口、付款回调、邮箱恢复和三台本人设备许可统一走金数据与 aixlg.com 许可服务。",
      highlights: [
        "购买按钮只打开服务端下发并通过域名校验的金数据 HTTPS 付款页。",
        "只有金数据返回付款成功、商品与金额完全一致时才签发许可。",
      ],
      previousHighlights: [
        "国外收款平台已退出当前运行链，历史记录只保留作审计依据。",
        "退款仍从金数据执行原路退回；后台确认后许可和设备凭证同步停用。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 98,
      dateText: "2026-07-28",
      title: "这版接上了金数据境内付款候选",
      summary: "购买按钮只接受许可服务返回并通过域名校验的金数据付款页；总闸关闭、配置异常或网络失败时继续保持不可付款。",
      highlights: [
        "付款入口只认生产金数据提供方和受信任的金数据 HTTPS 域名。",
        "付款后仍通过购买邮箱验证码恢复许可，App 不保存或直连任何金数据密钥。",
      ],
      previousHighlights: [
        "现有功能与许可强制继续关闭，不因形成候选而开放真实销售。",
        "三设备、Ed25519 离线凭证、退款撤权和本机钥匙串仍由既有许可服务约定负责。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 92,
      dateText: "2026-07-28",
      title: "这版让锁屏启动不再卡住",
      summary: "许可证钥匙串读取改到后台并设置有界降级，锁屏时主界面、快捷键和退出链继续响应。",
      highlights: [
        "钥匙串暂不可读时明确保持未授权，不误开付费能力，也不删除或覆盖本机许可证。",
        "启动读取不会弹出前台授权窗口；解锁后安全结果仍可恢复，不做无界重试。",
      ],
      previousHighlights: [
        "状态栏醒眠、Caps 核心键和用户快捷键配置保持不变。",
        "本候选只修启动期许可读取，不改 Checkout、官网或发布通道。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 91,
      dateText: "2026-07-27",
      title: "这版让状态栏的醒眠一按即换",
      summary: "点击菜单栏的醒 / 眠状态即可直接切换保持唤醒，不再先打开管理面板。",
      highlights: [
        "眠时点一下立即开启无限保持唤醒；醒时点一下立即恢复系统默认睡眠。",
        "点击只发送一次切换，不激活主窗口，也不抢走当前 App 的焦点。",
      ],
      previousHighlights: [
        "倒计时、自定义小时和保持屏幕亮起等高级选项继续保留在睡眠插件面板。",
        "状态栏开关、现有睡眠快捷键和用户配置保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 90,
      dateText: "2026-07-27",
      title: "这版让 Caps 更稳地接上快捷键",
      summary: "更新或重启后，Caps 会先保留系统事件降级通道，确认原始键盘输入已到达后再启用灭灯映射。",
      highlights: [
        "仅发现键盘设备不再被误判为 Caps 监听已就绪。",
        "HID 回调短暂未就绪时，Caps 不会先被映射成无动作，快捷键仍可走降级通道。",
      ],
      previousHighlights: [
        "确认收到原始键盘输入后，仍使用可恢复的 Caps 无动作映射抑制锁定灯短闪。",
        "不改用户现有快捷键、插件开关或权限配置。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 89,
      dateText: "2026-07-27",
      title: "这版把常用网址直接装好了",
      summary: "首次安装或恢复默认配置后，快捷短语直接带有 5 个常用网址缩写。",
      highlights: [
        "ppqd、ppdb、ppyy、ppvs 和 ppxlg 默认启用，输入后可直接展开对应网址。",
        "内置短语与恢复默认配置使用同一基线，不需要第一次手动重建。",
      ],
      previousHighlights: [
        "升级不会覆盖已有用户的快捷短语文件。",
        "新默认只包含明确的 HTTPS 网址，不携带本机 UUID 或其他用户状态。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 88,
      dateText: "2026-07-27",
      title: "这版让新装启动器更简洁",
      summary: "新装和恢复默认配置现在直接使用图标视图，固定项默认不显示名称。",
      highlights: [
        "已有用户的启动器显示偏好和快捷键配置保持不变。",
        "默认快捷键已同步为当前可通用基线，不再携带个人路径和过时动作。",
      ],
      previousHighlights: [
        "固定项名称仍保留在鼠标提示和辅助功能中，只减少界面文字。",
        "输入法、滚动、鼠标音量和网速等插件仍保持安全默认值。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 87,
      dateText: "2026-07-26",
      title: "这版让收费窗口只在真正可付款时开启",
      summary: "Pro 仍为 ¥299 买断；App 会先核验正式 Checkout，关闭时不再跳进未发布的购买页。",
      highlights: [
        "收费窗口明确显示 1 人最多 3 台本人 Mac、已购版本永久可用并含 12 个月功能更新。",
        "付款总闸关闭或网络核验失败时，购买按钮保持不可用并如实显示尚未开放。",
      ],
      previousHighlights: [
        "恢复购买入口继续保留，不把付款关闭误写成已经公开开售。",
        "现有功能继续可用，收费窗口同步不改变许可强制状态。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 86,
      dateText: "2026-07-26",
      title: "这版把 Pro 购买与恢复入口准备好了",
      summary: "关于页现在统一显示 ¥299 买断、恢复购买和许可状态；付费软启动不锁住现有功能。",
      highlights: [
        "购买获得一份 Pro 许可与 12 个月更新权，最多用于本人 3 台 Mac。",
        "收据使用 App 内公钥离线核验，私钥只保留在许可服务端。",
      ],
      previousHighlights: [
        "未完成生产收款验收前，网站付款总闸保持关闭。",
        "现有功能继续可用，软启动不会提前消耗旧用户未来试用期。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 85,
      dateText: "2026-07-26",
      title: "这版让设置快捷键跟手了",
      summary: "Caps + Esc 下方键不再等待松开 Caps，按下后会立即把设置动作交给触发时的前台 App。",
      highlights: [
        "前台是小龙哥Mac哲学时直接打开设置，不再绕一圈合成按键。",
        "其他 App 会锁定触发时的进程并定向发送 ⌘ + ,，不再受 Caps 松键速度或随后切换前台影响。",
      ],
      previousHighlights: [
        "同一次物理按下只触发一次，避免长按后连续打开两次。",
        "用户现有规则、Caps 键位映射和其他快捷键配置保持不变。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 84,
      dateText: "2026-07-26",
      title: "这版让快捷键录制更明白",
      summary: "重复录到已有快捷键时不再像没反应，而是说明现有用途并定位原规则。",
      highlights: [
        "Caps + Esc 下方键仍会向当前 App 发送 ⌘ + ,，用于快速打开支持该标准快捷键的设置页。",
        "再次录到相同组合时会显示已设置提示；清除临时筛选后按规则 ID 定位，不再受旧筛选结果阻挡。",
      ],
      previousHighlights: [
        "快捷键键位、Caps 核心映射和发送链路保持不变。",
        "本候选不改用户现有规则，也不恢复高频键盘内容监听。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 83,
      dateText: "2026-07-26",
      title: "这版让快捷键录制更明白",
      summary: "重复录到已有快捷键时不再像没反应，而是说明现有用途并定位原规则。",
      highlights: [
        "Caps + Esc 下方键仍会向当前 App 发送 ⌘ + ,，用于快速打开支持该标准快捷键的设置页。",
        "再次录到相同组合时会显示已设置提示；清除临时筛选后会等待列表布局完成，再定位到原规则。",
      ],
      previousHighlights: [
        "快捷键键位、Caps 核心映射和发送链路保持不变。",
        "本候选不改用户现有规则，也不恢复高频键盘内容监听。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 82,
      dateText: "2026-07-26",
      title: "这版让快捷键录制更明白",
      summary: "重复录到已有快捷键时不再像没反应，而是说明现有用途并定位原规则。",
      highlights: [
        "Caps + Esc 下方键仍会向当前 App 发送 ⌘ + ,，用于快速打开支持该标准快捷键的设置页。",
        "再次录到相同组合时会显示已设置提示并清除临时筛选，不创建重复项。",
      ],
      previousHighlights: [
        "快捷键键位、Caps 核心映射和发送链路保持不变。",
        "本候选不改用户现有规则，也不恢复高频键盘内容监听。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 81,
      dateText: "2026-07-26",
      title: "这版让快捷键录制更明白",
      summary: "重复录到已有快捷键时不再像没反应，而是说明现有用途并定位原规则。",
      highlights: [
        "Caps + Esc 下方键仍会向当前 App 发送 ⌘ + ,，用于快速打开支持该标准快捷键的设置页。",
        "再次录到相同组合时会显示已设置提示，并自动定位现有“偏好设置”规则，不创建重复项。",
      ],
      previousHighlights: [
        "快捷键键位、Caps 核心映射和发送链路保持不变。",
        "本候选不改用户现有规则，也不恢复高频键盘内容监听。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 80,
      dateText: "2026-07-26",
      title: "这版把启动、输入与卸载收得更稳",
      summary: "启动器更克制，输入法按明确 App 低频切换，安全卸载会说明真实结果；安装包也换成了更清楚的原生拖拽界面。",
      highlights: [
        "启动器收起多余说明，支持从 App 右键发起安全卸载；完成后列表立即刷新，系统保护数据会明确保留。",
        "输入法管家默认关闭，只按已配置 App 或本 App 独立窗口切换，并提供规则备份、恢复与失效诊断。",
        "Caps 核心键使用可确认、可恢复的系统映射，降低快速按键时锁定灯短闪，并在停用或退出时恢复原设置。",
      ],
      previousHighlights: [
        "插件中心只保留完整能力，小型系统动作回到设置或系统入口。",
        "正式安装包采用 Developer ID 签名、公证与极简拖拽布局；更新仍会校验版本、签名和 SHA256。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 54,
      dateText: "2026-07-20",
      title: "这版让主界面更克制，更新更直接",
      summary: "主界面只保留高频动作；发现正式新版后，可在 App 内安全下载、校验、安装并重启。",
      highlights: [
        "功能快捷键首页收口为搜索、筛选、浏览、启停和编辑，维护项移入设置。",
        "品牌区直接显示当前版本；实时按键测试默认关闭，只在用户主动开启时监听。",
        "发现更高 build 后显示更新入口，下载过程展示真实进度，并校验 SHA、Bundle ID、Developer ID、公证票据和 Gatekeeper。",
      ],
      previousHighlights: [
        "更新失败不会替换当前 App；安装失败会恢复旧版本并给出可重试说明。",
        "正式发布以 Developer ID 签名、Apple 公证、staple 和线上 SHA 回拉为准。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 52,
      dateText: "2026-07-05",
      title: "这版做了收工前复盘和官网同步",
      summary: "把最近几轮已验证的本地修复收进官网 LocalTest 包，并继续保持非公证测试包边界。",
      highlights: [
        "应用内检查更新改为信任 aixlg.com，不再被旧 tlww.cn 校验拦住。",
        "功能快捷键首页分类收口：第三方截图、翻译、OCR 记录归入截图类，截图类预览显示 Caps + 1。",
        "插件中心更克制：普通路径不再展示新增插件入口，恢复默认配置迁移到设置里的故障恢复。",
      ],
      previousHighlights: [
        "仍是 LocalTest 官网分发包，不是 Developer ID notarized 正式公证包。",
        "Caps + Q、千问发送快捷键、Command + Tab 恢复等真实物理验收仍按 issue 单独保留。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 46,
      dateText: "2026-06-28",
      title: "这版把官网默认下载切到 DMG",
      summary: "官网第一下载入口改为 DMG 安装包，同时把新装机默认快捷键基线修复带进发布包。",
      highlights: [
        "官网默认下载改为 DMG，打开后把「小龙哥Mac哲学.app」拖到 Applications。",
        "新装默认不再出现旧「打开 aixlg 军火库 / Caps + ⌘ + J」主规则。",
        "「打开快捷键面板」默认基线更新为 Caps + ⌘ + E，旧默认配置会迁移，用户自定义不会被静默覆盖。",
      ],
      previousHighlights: [
        "ZIP 仍保留给应用内自动更新通道和备用下载。",
        "当前包仍是 LocalTest 官网分发，不是 Developer ID 公证包。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 45,
      dateText: "2026-06-26",
      title: "这版把常用脚本和打开 App 口径收清楚",
      summary: "常用脚本、切换麦克风和打开 App 的显示口径一起修复，固定预设和可自定义入口不再混在一起。",
      highlights: [
        "动作菜单里的「常用脚本」收纳打开 Emoji 与符号、切换麦克风、启动器、休眠、息屏等固定预设。",
        "「麦克风」统一改成「切换麦克风」，失败时会显示可理解原因，不再只报退出码 1。",
        "「打开 App」只保留给能自行选择 App / 文件 / 文件夹的入口，固定系统动作和固定预设归入「常用脚本」。",
      ],
      previousHighlights: [
        "上一版已把 Windows 式 Tab 切换收口到 AltTab 主路线。",
        "当前包仍是 LocalTest 官网更新通道，不是 Developer ID 公证包。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 44,
      dateText: "2026-06-24",
      title: "这版把 Windows 式 Tab 切换收口到 AltTab 主路线",
      summary: "完整 Windows 式窗口切换交给 AltTab，本 App 内置切换器只保留为备用，避免两个工具抢同一个快捷键。",
      highlights: [
        "Windows 式 Alt+Tab 体验改为 AltTab 优先，本 App 负责说明、检测和让路。",
        "插件中心文案已改为「AltTab 优先 / 内置备用」，内置 Classic Tab 默认关闭。",
        "官网、更新日志和下载清单同步说明：这是 LocalTest 更新通道，不是 Developer ID 公证包。",
      ],
      previousHighlights: [
        "上一版修复了更新公告里的「查看更新日志」链接。",
        "真实 Option + Tab 手感仍以小龙哥本机肉眼复验为准。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 43,
      dateText: "2026-06-22",
      title: "这版修复更新公告的更新日志链接",
      summary: "更新后第一次打开会提示一次；点「知道了」后，同一个版本不会再重复出现。",
      highlights: [
        "更新公告里的「查看更新日志」现在会打开 https://aixlg.com/changelog.html。",
        "不再把「查看更新日志」带到官网首页，方便直接查看每次发布记录。",
        "这是链接小修复，不改 Karabiner、Caps、快捷键或滚轮业务逻辑。",
      ],
      previousHighlights: [
        "上一版已把入口键方向切回 Karabiner-Elements，本 App 只保留规则一键导入。",
        "更新包仍会校验 SHA256、Bundle ID、构建号和签名后再安装。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 42,
      dateText: "2026-06-22",
      title: "这版把入口键方向切回 Karabiner",
      summary: "更新后第一次打开会提示一次；点「知道了」后，同一个版本不会再重复出现。",
      highlights: [
        "入口键方向改为由 Karabiner-Elements 负责，本 App 只提供 Caps Lock -> Control + Option 规则一键导入。",
        "已移除自研 Caps 入口键 / Caps Core Plugin，避免新系统里自研监听不稳定。",
        "插件中心保留 Karabiner 规则导入入口，不自动下载、不自动安装、不改真实权限。",
      ],
      previousHighlights: [
        "上一版 build 41 是 Caps 默认开启过渡包，已被 Karabiner 方向覆盖。",
        "更新包仍会校验 SHA256、Bundle ID、构建号和签名后再安装。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 41,
      dateText: "2026-06-22",
      title: "这版修复新机器 Caps 入口键默认关闭",
      summary: "更新后第一次打开会提示一次；点「知道了」后，同一个版本不会再重复出现。",
      highlights: [
        "新机器首次启动时，Caps 入口键默认开启，不再显示成默认关闭 / 未监听。",
        "老用户如果已经手动关闭 Caps 入口键，升级后仍会保留关闭选择。",
        "插件中心关闭态文案改为「已关闭」，避免把用户手动关闭误说成默认策略。",
      ],
      previousHighlights: [
        "上一版已发布整枚 Caps 键帽图标、官网品牌故事和更新日志纪律。",
        "更新包仍会校验 SHA256、Bundle ID、构建号和签名后再安装。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 40,
      dateText: "2026-06-22",
      title: "这版把图标、官网故事和更新记录一起收口",
      summary: "更新后第一次打开会提示一次；点「知道了」后，同一个版本不会再重复出现。",
      highlights: [
        "应用图标升级为整枚 Caps 键帽，强化小拇指触发和左手入口的识别感。",
        "官网补入「左手掌控 Mac 一切」与 80% 高频场景的品牌故事。",
        "更新日志补齐长期记录纪律，后续每次版本更新都要留下清楚说明。",
      ],
      previousHighlights: [
        "菜单栏网速、睡眠插件、Command + W 和缺 Chrome 快捷键占用已在上一版收口。",
        "官网已经升级为 AI 小龙哥 / 小龙哥的 OS 哲学口径。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
    ReleaseNoteEntry(
      version: "0.6.7",
      build: 39,
      dateText: "2026-06-21",
      title: "这版把发布前几个体验问题收掉了",
      summary: "更新后第一次打开会提示一次；点「知道了」后，同一个版本不会再重复出现。",
      highlights: [
        "菜单栏网速和 RAM 字号比例更接近系统状态栏。",
        "睡眠已进入插件中心，常用开关集中在同一处。",
        "Command + W 恢复为关闭当前窗口，App 仍在后台常驻。",
        "缺少 Chrome 时，浏览器快捷键不会再被旧 Chrome 规则幽灵占用。",
      ],
      previousHighlights: [
        "官网 V0.7 已补齐功能快捷键说明。",
        "应用内更新通道已可检查、下载、校验并安装新版。",
      ],
      changelogURL: fallbackChangelogURL,
    ),
  ]

  static func entry(forBuild build: Int) -> ReleaseNoteEntry? {
    bundled.first { $0.build == build }
  }
}
